# Generated by Django 3.2.3 on 2021-05-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='dateOfBirth',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
    ]
