# Generated by Django 3.2.3 on 2021-05-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='hello', max_length=255),
        ),
        migrations.AlterField(
            model_name='dojo',
            name='title',
            field=models.CharField(default='moath11', max_length=45),
        ),
    ]
